### ISSUE TITLE
Unable to use floating point values in math expressions

### ISSUE THREAD

**Issue by shepmaster** [rzane/baby_squeel#41]
#### Issue

I'd like to be able to write something like `Dog.selecting { (coalesce(id, 0) / 42.42).as('value') }`, but it appears I cannot use floating point numbers:

```
RuntimeError: unsupported: Float
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:735:in `unsupported'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:756:in `visit_Arel_Nodes_InfixOperation'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:699:in `visit_Arel_Nodes_As'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:241:in `block in visit_Arel_Nodes_SelectCore'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:240:in `each'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:240:in `each_with_index'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:240:in `visit_Arel_Nodes_SelectCore'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:210:in `block in visit_Arel_Nodes_SelectStatement'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:209:in `each'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:209:in `inject'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:209:in `visit_Arel_Nodes_SelectStatement'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/sqlite.rb:13:in `visit_Arel_Nodes_SelectStatement'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
    ~/.rvm/gems/ruby-2.3.1/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:7:in `accept'
    ~/.rvm/gems/ruby-2.3.1/gems/activerecord-4.2.5.2/lib/active_record/relation.rb:551:in `to_sql'
```

I note that the stacktrace doesn't mention baby_squeel at all, so it's possible that this issue is outside of the scope of this library?

#### Reproduction

```ruby
require 'bundler/inline'
require 'minitest/spec'
require 'minitest/autorun'

gemfile true do
  source 'https://rubygems.org'
  gem 'activerecord', '~> 4.2.5.1'
  gem 'sqlite3'
  gem 'baby_squeel', github: 'rzane/baby_squeel'
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :dogs, force: true do |t|
    t.string :name
  end
end

class Dog < ActiveRecord::Base
end

class BabySqueelTest < Minitest::Spec
  it 'works' do
    scope = Dog.selecting { (coalesce(id, 0) / 42.42).as('value') }
  end
end
```

**Comment by asaletnik** [comment]
I had similar issue after upgrading to Rails 4.2.x, and I've been struggling to find solution for some time, here's what I had problem with:
```
where.has {|t| t.date_format(t.birthday_at, '%d/%m') }
```
has been giving me:
```
RuntimeError:
  unsupported: String
  # ./config/initializers/arel.rb:761:in `unsupported'
  # ./config/initializers/arel.rb:15:in `visit'
  (etc...)
```
I've tracked the exception, and it was raised because of that `'%d/%m' string. I also didn't see BabySqueel anywhere in the backtrace, so at first I didn't suspect that.

This is what helped in my case:
```
where.has {|t| t.date_format(t.birthday_at, t.quoted('%d/%m')) }
```

I've used `quoted` method implemented here:
https://github.com/rzane/baby_squeel/blob/master/lib/baby_squeel/dsl.rb#L91

Doing the same in your case should probably help :)
```
Dog.selecting { (coalesce(id, 0) / quoted(42.42)).as('value') }
```

**Comment by rzane** [comment]
Thanks, @asaletnik. Quoted is probably the way to go here. I'm nervous to try and "infer" what to do with arguments to functions.

Basically, anytime you get an error like `unsupported`, you probably need a SqlLiteral. Quoted will call `YourModel.connection.quote` on the connection adapter and then convert to a SqlLiteral, which Arel will happily accept.
