### ISSUE TITLE
Where.has for polymorphic fields

### ISSUE THREAD

**Issue by hlogmans** [rzane/baby_squeel#43]
#### Issue

Where.has does not work as smart as Arel with polymorphic fields. I've build a simplified case to demonstrate this. It seems something is simplified before it gets transported to Arel, as Arel itself does support these cases. For a workaround I use Arel directly, but the BabySqueel code is soo much nicer :)

I tried to create changes in BabySqueel to support it, but I did not succeed to find the place to intercept this behaviour.

Notice: Arel also does understand the case where the polymorphic relation test is a relation itself, like Dropping.where(animal: dogs). dogs is a relationship.

With some pointers how to solve it I can also contribute to this gem and create a pull request.

#### Reproduction

```ruby
require 'bundler/inline'
require 'minitest/spec'
require 'minitest/autorun'

gemfile true do
  source 'https://rubygems.org'
  gem 'activerecord', '~> 5.0.0' # which Active Record version?
  gem 'sqlite3'
  gem 'baby_squeel', github: 'rzane/baby_squeel'
end

ActiveRecord::Base.establish_connection(adapter: 'sqlite3', database: ':memory:')

ActiveRecord::Schema.define do
  create_table :dogs, force: true do |t|
    t.string :name
  end

  create_table :droppings, force: true do |t|
    t.string :animal_type
    t.integer :animal_id
  end
end

class Dog < ActiveRecord::Base
end

class Dropping < ActiveRecord::Base
  belongs_to :animal, polymorphic: true
end

class BabySqueelTest < Minitest::Spec
  it 'works' do
    localtext = 'Fido'
    scope = Dog.where.has { name == localtext }

    scope.to_sql.must_equal %{
      SELECT "dogs".* FROM "dogs" WHERE "dogs"."name" = 'Fido'
    }.squish
  end

  it 'works with Arel' do
    dog = Dog.create(name: 'Fido')

    scope = Dropping.where(animal: dog)

    scope.to_sql.must_equal %{
      SELECT "droppings".* FROM "droppings" WHERE "droppings"."animal_type" = 'Dog' AND "droppings"."animal_id" = #{dog.id}
    }.squish
  end

  it 'works for babysqueel polymorphic' do
    dog = Dog.create(name: 'Fido')

    scope = Dropping.where.has{animal == dog}

    scope.to_sql.must_equal %{
      SELECT "droppings".* FROM "droppings" WHERE "droppings"."animal_type" = 'Dog' AND "droppings"."animal_id" = #{dog.id}
    }.squish
  end
end
```

#### output
```
BabySqueelTest#test_0003_works for babysqueel polymorphic:
ArgumentError: Unsupported argument type: false (FalseClass)
    /Users/hlogmans/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.1/lib/active_record/relation/where_clause_factory.rb:27:in `build'
    /Users/hlogmans/.rvm/gems/ruby-2.3.0/gems/activerecord-5.0.1/lib/active_record/relation/query_methods.rb:632:in `where!'
    /Users/hlogmans/.rvm/gems/ruby-2.3.0/bundler/gems/baby_squeel-31e364f6644d/lib/baby_squeel/active_record/where_chain.rb:9:in `has'
    test.rb:55:in `block in <class:BabySqueelTest>'
```

**Comment by rzane** [comment]
Thanks so much for putting the time in to investigate. I really appreciate that! Sorry I took so long to get back to you!

This will land in the next version. Unfortunately, it's slightly trickier to implement for Active Record <=4, so I'm only going to implement it for 5+.
